### ISSUE TITLE
Minimize the Amount of Guided Packages

### ISSUE THREAD

**Issue by zzqwdwd** [linjing-lab/optimtool#3]
Is it necessary to reconstruct the matrix operation system of  `numpy`  and the symbolic algebra operation system of `sympy` in order to reduce the amount of dependent packets in the process of guilding packets.

**Comment by linjing-lab** [comment]
> Is it necessary to reconstruct the matrix operation system of `numpy` and the symbolic algebra operation system of `sympy` in order to reduce the amount of dependent packets in the process of guilding packets.

**Comment by linjing-lab** [comment]
> Is it necessary to reconstruct the matrix operation system of `numpy` and the symbolic algebra operation system of `sympy` in order to reduce the amount of dependent packets in the process of guilding packets.

Obviously, in the process of designing an open source package, if you rely on too many third-party packages, it will cause another burden in the subsequent maintenance process. In order to reduce the burden, it is necessary to design a separate matrix operation system for this optimization algorithm system in the algebraic symbol operation system.
