### ISSUE TITLE
Extended Interior Point Method Function

### ISSUE THREAD

**Issue by Jianguo99** [linjing-lab/optimtool#4]
When can this open-source package supplement the function library of the interior point method and run stably?

**Comment by linjing-lab** [comment]
> When can this open-source package supplement the function library of the interior point method and run stably?

Because the interior point method in the penalty function method will overflow iterative points in the program when calling the unconstrained kernel, it is difficult to realize the penalty function optimization method through the interior point method. However, we will try our best to solve these problems to ensure that researchers can use the most stable method as soon as possible.
