### ISSUE TITLE
Gradient Disappearance and Explosion

### ISSUE THREAD

**Issue by Fatflower** [linjing-lab/optimtool#5]
How to solve the division by 0 problem in the operation of the algorithm and the disappearance of gradient without reason.

**Comment by linjing-lab** [comment]
> How to solve the division by 0 problem in the operation of the algorithm and the disappearance of gradient without reason.

Many times, when dealing with the influence factor of the algorithm (gradient, Heather matrix), I often encounter the situation of dividing by 0. However, in order to ensure the integrity of the original method framework, I generally do not deal with it when designing the algorithm. A mechanism will be designed in the future for error handling, such as the gradient disappearance and gradient descent problem you mentioned.
